# fly.toml file generated for superlettredemotivation on 2023-05-23T17:38:42+02:00

app = "superlettredemotivation"
primary_region = "cdg"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  APP_ENV = "production"
  APP_URL = "https://superlettredemotivation.fly.dev"
  APP_NAME="Super Lettre de Motivation"
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.leaohztxokfoyzzgjdoh.supabase.co"
  DB_PORT = 5432
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"
  DB_PASSWORD = "oPknXy64XaYQ3EJGemjB"
  OPENAI_API_KEY = "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"
  GOOGLE_CLIENT_ID = "1004553041407-cte7maspj59l2mtmnqucd7tn1orda849.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET = "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"
  GOOGLE_REDIRECT = "https://superlettredemotivation.fly.dev/auth/google/callback"
  GOOGLE_PASSWORD = "8WanhB@pA4$4$PzYnpBE0"
  POLE_EMPLOI_CLIENT_ID = "PAR_superlettredemotivati_5e9363e44cf5661938b5cb7226aca5b506dd25e4e12423b77e937e22fc9c2b63"
  POLE_EMPLOI_CLIENT_SECRET = "8df856146f19140670c82d773d77d6ae2843f9df5923cd355a01feb3b3bedcc5"
  POLE_EMPLOI_SCOPE = "nomenclatureRome api_rome-metiersv1"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
