# fly.toml app configuration file generated for lettredemotivation on 2024-02-07T20:41:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lettredemotivation'
primary_region = 'cdg'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_DEBUG = 'true'
  APP_ENV = 'production'
  APP_NAME = 'Lettre de Motivation - Exemple Lettre de Motivation'
  APP_URL = 'https://lettredemotivation.app'
  DB_CONNECTION = 'pgsql'
  DB_DATABASE = 'postgres'
  DB_HOST = 'db.leaohztxokfoyzzgjdoh.supabase.co'
  DB_PORT = '5432'
  DB_USERNAME = 'postgres'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  MAIL_MAILER = 'smtp'
  MAIL_FROM_ADDRESS = 'no-reply@lettredemotivation.app'
  MAIL_FROM_NAME = 'Lettre de Motivation'
  MAIL_ENCRYPTION = 'tls'
  MAIL_CONTACT= 'contact@lettredemotivation.app'
  MAIL_HOST = 'mail.smtp2go.com'
  MAIL_PORT = 2525
  MAIL_USERNAME = 'lettredemotivation.app'
  OPENAI_MODEL = 'gpt-4'
  REDIS_HOST = 'lettredemotivation-redis.internal'
  REDIS_CLIENT = 'predis'
  CACHE_DRIVER = 'redis'
  SESSION_DRIVER = 'redis'
  REDIS_DB = 0
  REDIS_CACHE_DB = 0
  POLE_EMPLOI_SCOPE = 'nomenclatureRome api_rome-metiersv1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
