# fly.toml app configuration file generated for lettredemotivation-redis on 2024-02-07T21:16:51+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lettredemotivation-redis'
primary_region = 'cdg'

[build]
  image = 'flyio/redis:6.2.6'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[mounts]]
  destination = "/data"
  source = "redis_server"
